import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from '@src/app/app.component';
import { DemoLibModule } from '@company/demo-lib';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';

@NgModule({
  declarations: [AppComponent, AutoGeneratedComponent],
  imports: [BrowserModule, DemoLibModule],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
